version: "2"

services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default
  wp:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${ID}-wp.rule=Host(`${HOST}`) || Host(`www.${HOST}`)"
      - "traefik.http.routers.${ID}-wp.entrypoints=websecure"
      - "traefik.http.services.${ID}-wp.loadbalancer.server.port=80"
      - "traefik.http.routers.${ID}-wp.service=${ID}-wp"
      - "traefik.http.routers.${ID}-wp.tls.certresolver=leresolver"
    volumes:
      - wp_content:/var/www/html/wp-content
    networks:
      - default
      - traefik
  ssh:
    image: ghcr.io/linuxserver/openssh-server
    restart: always
    environment:
      - PUID=33
      - PGID=33
      - TZ=Europe/Berlin
      - PASSWORD_ACCESS=true
      - USER_NAME=${ID}
      - USER_PASSWORD=${SSH_PASSWORD}
      - DOCKER_MODS=linuxserver/mods:openssh-server-ssh-tunnel
    volumes:
      - ssh_config:/config
      - wp_content:/var/www/html/wp-content
    ports:
      - 2222
    networks:
      - default
  pma:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_DATABASE_PASSWORD}
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${ID}-pma.rule=(Host(`${HOST}`) || Host(`www.${HOST}`)) && PathPrefix(`/__db`)"
      - "traefik.http.routers.${ID}-pma.entrypoints=websecure"
      - "traefik.http.services.${ID}-pma.loadbalancer.server.port=80"
      - "traefik.http.routers.${ID}-pma.service=${ID}-pma"
      - "traefik.http.routers.${ID}-pma.tls.certresolver=leresolver"
      - "traefik.http.middlewares.${ID}-pma-stripprefix.stripprefix.prefixes=/__db"
      - "traefik.http.middlewares.${ID}-pma-auth.basicauth.users=${PMA_USERS}"
      - "traefik.http.middlewares.${ID}-pma-auth.basicauth.removeheader=true"
      - "traefik.http.routers.${ID}-pma.middlewares=${ID}-pma-auth,${ID}-pma-stripprefix"
  code:
    image: ghcr.io/linuxserver/code-server
    restart: unless-stopped
    environment:
      - PUID=33
      - PGID=33
      - TZ=Europe/Berlin
    volumes:
      - code_config:/config
      - wp_content:/config/workspace/wp-content
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${ID}-code.rule=Host(`${CODE_HOST}`)"
      - "traefik.http.routers.${ID}-code.entrypoints=websecure"
      - "traefik.http.services.${ID}-code.loadbalancer.server.port=8443"
      - "traefik.http.routers.${ID}-code.service=${ID}-code"
      - "traefik.http.routers.${ID}-code.tls.certresolver=leresolver"
      - "traefik.http.middlewares.${ID}-code-auth.basicauth.users=${CODE_USERS}"
      - "traefik.http.middlewares.${ID}-code-auth.basicauth.removeheader=true"
      - "traefik.http.routers.${ID}-code.middlewares=${ID}-code-auth"
    networks:
      - traefik

volumes:
  db_data:
    driver: local
  wp_content:
    driver: local
  ssh_config:
    driver: local
  code_config:
    driver: local

networks:
  default:
    external: false
  traefik:
    external:
      name: traefik
